

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: swift
    - os: linux
      dist: trusty
      language: cpp
     
before_install:
  - chmod ugo+x ./install_swift.bash
  - . ./install_swift.bash

script:
  - uname -a
  - swift build
  - swift test
  - 

after_success:
  - bash <(curl -s https://codecov.io/bash)
