

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: swift
    - os: linux
      dist: trusty
      language: cpp
     
before_install:
  - chmod ugo+x ./install_swift.bash
  - . ./install_swift.bash

script:
  - uname -a
  - swift build
  - swift test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make codecov ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash <(curl -s https://codecov.io/bash); fi
